sudo: required
language: bash
services:
- docker
branches:
  only:
  - master
before_install:
- nvm install 6.8.1
- nvm use 6.8.1
- npm install -g yarn npm@'>=3'
install:
- yarn install
script:
- docker pull ubuntu:latest
- npm run coverage