app:
  image: node:6.9.1-slim
  ports:
      - "3000:3000"
  working_dir: /code
  volumes:
    - ./:/code
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - ENV=ci
  command: npm start
